FROM maven:3.8.6-openjdk-8-slim AS build

WORKDIR /app

COPY pom.xml .
COPY src src

RUN mvn clean package -DskipTests

#----------------------------------------------

FROM eclipse-temurin:8-jre-alpine-3.22

WORKDIR /app

COPY --from=build /app/target/Toy0Store.jar .

CMD ["java", "-jar", "Toy0Store.jar"]
